# A new appspec.yaml will be generated in the buildspec.yaml file. This file is for reference only.
version: 0.0
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: task-definition-arn-from-stack
        LoadBalancerInfo:
          ContainerName: container-name-from-stack
          ContainerPort: 3000
