AWSTemplateFormatVersion: '2010-09-09'

Parameters:
  GitHubRepoOwner:
    Type: String
    Description: GitHub repository owner
  GitHubRepoName:
    Type: String
    Description: GitHub repository name
  GitHubBranch:
    Type: String
    Default: main
    Description: GitHub branch to trigger the pipeline
  UniqueID:
    Type: String
    Default: commit-hash
    Description: ID for unique resource naming
  ImageRepositoryName:
    Type: String
    Default: my-ecr-repo
    Description: Name of the Amazon ECR repository
  # S3BucketName:
  #   Type: String
  #   Default: !Sub '${UniqueID}-bucket'
  # ContainerName:
  #   Type: String
  #   Default: !Sub '${UniqueID}-container'

Resources:
  MyS3Bucket:
    Type: 'AWS::S3::Bucket'
    DeletionPolicy: Delete
    Properties:
      BucketName: !Sub '${UniqueID}-bucket'

  # MySeedStack:
  #   Type: AWS::CloudFormation::Stack
  #   Properties:
  #     TemplateURL: https://hydra-cfn-templates-stage.s3.amazonaws.com/seed-stack.yaml
  #     Parameters:
  #       ImageRepositoryName: !Ref ImageRepositoryName
  #       S3Bucket: !Ref MyS3Bucket
  #       S3BucketName: !Ref S3BucketName
  #       GitHubRepoOwner: !Ref GitHubRepoOwner
  #       GitHubRepoName: !Ref GitHubRepoName
  #       GitHubBranch: !Ref GitHubBranch

  MyLogGroup:
    Type: 'AWS::Logs::LogGroup'
    Properties:
      LogGroupName: !Sub '/ecs/${UniqueID}/MyLogGroup'

  MyVPC:
    Type: 'AWS::EC2::VPC'
    Properties:
      CidrBlock: '10.0.0.0/16'
      EnableDnsSupport: true
      EnableDnsHostnames: true
      Tags:
        - Key: Name
          Value: !Sub '${UniqueID}-vpc'

  MyInternetGateway:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
        - Key: Name
          Value: !Sub '${UniqueID}-gateway'

  MyInternetGatewayAttachment:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      InternetGatewayId: !Ref MyInternetGateway
      VpcId: !Ref MyVPC

  PublicSubnetA:
    Type: 'AWS::EC2::Subnet'
    Properties:
      AvailabilityZone: !Select [0, !GetAZs '']
      CidrBlock: '10.0.1.0/24'
      VpcId: !Ref MyVPC
      MapPublicIpOnLaunch: true
      Tags:
        - Key: Name
          Value: !Sub '${UniqueID}-PublicSubnetA'

  PublicSubnetB:
    Type: 'AWS::EC2::Subnet'
    Properties:
      AvailabilityZone: !Select [1, !GetAZs '']
      CidrBlock: '10.0.2.0/24'
      VpcId: !Ref MyVPC
      MapPublicIpOnLaunch: true
      Tags:
        - Key: Name
          Value: !Sub '${UniqueID}-PublicSubnetB'

  PrivateSubnetA:
    Type: 'AWS::EC2::Subnet'
    Properties:
      AvailabilityZone: !Select [0, !GetAZs '']
      CidrBlock: '10.0.3.0/24'
      VpcId: !Ref MyVPC
      Tags:
        - Key: Name
          Value: !Sub '${UniqueID}-PrivateSubnetA'

  PrivateSubnetB:
    Type: 'AWS::EC2::Subnet'
    Properties:
      AvailabilityZone: !Select [1, !GetAZs '']
      CidrBlock: '10.0.4.0/24'
      VpcId: !Ref MyVPC
      Tags:
        - Key: Name
          Value: !Sub '${UniqueID}-PrivateSubnetB'

  PublicRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref MyVPC
      Tags:
        - Key: Name
          Value: !Sub '${UniqueID}-PublicRouteTable'

  PublicRouteTableAssociationA:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref PublicSubnetA
      RouteTableId: !Ref PublicRouteTable

  PublicRouteTableAssociationB:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref PublicSubnetB
      RouteTableId: !Ref PublicRouteTable

  PublicRoute:
    Type: AWS::EC2::Route
    DependsOn: MyInternetGatewayAttachment
    Properties:
      RouteTableId: !Ref PublicRouteTable
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref MyInternetGateway

  MyALB:
    Type: 'AWS::ElasticLoadBalancingV2::LoadBalancer'
    DependsOn:
      - MyInternetGateway
      - MyInternetGatewayAttachment
    Properties:
      Name: !Sub '${UniqueID}-MyALB'
      Subnets:
        - !Ref PublicSubnetA
        - !Ref PublicSubnetB
      SecurityGroups:
        - !GetAtt MyALBSecurityGroup.GroupId
      Scheme: internet-facing
      Tags:
        - Key: Name
          Value: !Sub '${UniqueID}-MyALB'

  MyALBListener:
    Type: 'AWS::ElasticLoadBalancingV2::Listener'
    DependsOn:
      - MyECSServiceRole
    Properties:
      DefaultActions:
        - Type: forward
          ForwardConfig:
            TargetGroups:
              - TargetGroupArn: !Ref MyTargetGroup
                Weight: 1
      LoadBalancerArn: !Ref MyALB
      Port: 80
      Protocol: HTTP

  MyTargetGroup:
    Type: 'AWS::ElasticLoadBalancingV2::TargetGroup'
    Properties:
      Name: !Sub '${UniqueID}-MyTargetGroup1'
      Port: 80
      Protocol: HTTP
      VpcId: !Ref MyVPC
      TargetType: ip # Set the target type to ip
      HealthCheckIntervalSeconds: 30
      HealthCheckProtocol: HTTP
      HealthCheckPath: '/'
      HealthCheckPort: traffic-port
      HealthCheckTimeoutSeconds: 5
      HealthyThresholdCount: 2
      UnhealthyThresholdCount: 2
      Tags:
        - Key: Name
          Value: !Sub '${UniqueID}-MyTargetGroup1'

  MySecondTargetGroup:
    Type: 'AWS::ElasticLoadBalancingV2::TargetGroup'
    Properties:
      Name: !Sub '${UniqueID}-MyTargetGroup2'
      Port: 80
      Protocol: HTTP
      VpcId: !Ref MyVPC
      TargetType: ip # Set the target type to ip
      HealthCheckIntervalSeconds: 30
      HealthCheckProtocol: HTTP
      HealthCheckPath: '/'
      HealthCheckPort: traffic-port
      HealthCheckTimeoutSeconds: 5
      HealthyThresholdCount: 2
      UnhealthyThresholdCount: 2
      Tags:
        - Key: Name
          Value: !Sub '${UniqueID}-MyTargetGroup2'

  MyALBSecurityGroup:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      GroupName: !Sub '${UniqueID}-MyALBSecurityGroup'
      GroupDescription: 'Allow traffic to ALB'
      VpcId: !Ref MyVPC
      SecurityGroupIngress:
        - CidrIp: '0.0.0.0/0'
          IpProtocol: -1
      Tags:
        - Key: Name
          Value: !Sub '${UniqueID}-MyALBSecurityGroup'

  MyECSCluster:
    Type: 'AWS::ECS::Cluster'
    Properties:
      ClusterName: !Sub '${UniqueID}-MyECSCluster'

  MyECSTaskDefinition:
    Type: 'AWS::ECS::TaskDefinition'
    Properties:
      Family: !Sub '${UniqueID}-MyECSTask'
      NetworkMode: awsvpc
      Memory: 2048 # Specify the amount of memory in MiB
      Cpu: 1024
      ExecutionRoleArn: !GetAtt MyECSTaskExecutionRole.Arn
      RequiresCompatibilities:
        - FARGATE
      RuntimePlatform:
        CpuArchitecture: ARM64
        OperatingSystemFamily: LINUX
      ContainerDefinitions:
        - Name: !Sub '${UniqueID}-container'
          Image: !Sub '${AWS::AccountId}.dkr.ecr.${AWS::Region}.amazonaws.com/${ImageRepositoryName}:latest'
          Memory: 2048 # Specify the amount of memory in MiB
          Cpu: 1024
          PortMappings:
            - ContainerPort: 3000
              HostPort: 3000
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-group: !Sub '/ecs/${UniqueID}/MyLogGroup'
              awslogs-region: us-east-1
              awslogs-stream-prefix: !Sub '${UniqueID}-container'

  MyECSTaskExecutionRole:
    Type: 'AWS::IAM::Role'
    Properties:
      RoleName: !Sub '${UniqueID}-MyECSTaskExecutionRole'
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: ecs-tasks.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: !Sub '${UniqueID}-ECSExecutionRolePolicy'
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - ecr:GetAuthorizationToken
                  - ecr:BatchCheckLayerAvailability
                  - ecr:GetDownloadUrlForLayer
                  - ecr:BatchGetImage
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: '*'

  MyECSService:
    Type: 'AWS::ECS::Service'
    DependsOn: MyALBListener
    Properties:
      ServiceName: !Sub '${UniqueID}-MyECSService'
      Cluster: !Ref MyECSCluster
      DesiredCount: 1 # Adjust as needed
      TaskDefinition: !Ref MyECSTaskDefinition
      LaunchType: FARGATE
      DeploymentController:
        Type: CODE_DEPLOY
      LoadBalancers:
        - ContainerName: !Sub '${UniqueID}-container'
          ContainerPort: 3000
          TargetGroupArn: !Ref MyTargetGroup
      NetworkConfiguration:
        AwsvpcConfiguration:
          AssignPublicIp: ENABLED
          Subnets:
            - !Ref PublicSubnetA
            - !Ref PublicSubnetB
          SecurityGroups:
            - !GetAtt MyECSSecurityGroup.GroupId

  MyECSServiceRole:
    Type: 'AWS::IAM::Role'
    Properties:
      RoleName: !Sub '${UniqueID}-MyECSServiceRole'
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - ecs.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      Path: /
      Policies:
        - PolicyName: !Sub '${UniqueID}-ecs-service'
          PolicyDocument:
            Statement:
              - Effect: Allow
                Action:
                  - 'elasticloadbalancing:DeregisterInstancesFromLoadBalancer'
                  - 'elasticloadbalancing:DeregisterTargets'
                  - 'elasticloadbalancing:Describe*'
                  - 'elasticloadbalancing:RegisterInstancesWithLoadBalancer'
                  - 'elasticloadbalancing:RegisterTargets'
                  - 'ec2:Describe*'
                  - 'ec2:AuthorizeSecurityGroupIngress'
                Resource: '*'

  MyECSSecurityGroup:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      GroupName: !Sub '${UniqueID}-MyECSSecurityGroup'
      GroupDescription: 'Allow traffic to ECS tasks'
      VpcId: !Ref MyVPC
      SecurityGroupIngress:
        - IpProtocol: -1
          SourceSecurityGroupId: !GetAtt MyALBSecurityGroup.GroupId
      SecurityGroupEgress:
        - IpProtocol: -1
          CidrIp: '0.0.0.0/0' # Allow outbound traffic to the internet

  MyCodeBuildProject:
    Type: 'AWS::CodeBuild::Project'
    Properties:
      Name: !Sub '${UniqueID}-MyCodeBuildProject'
      Description: My CodeBuild Project
      ServiceRole: !GetAtt MyCodeBuildRole.Arn
      Source:
        Type: CODEPIPELINE
      Environment:
        Type: ARM_CONTAINER
        ComputeType: BUILD_GENERAL1_SMALL
        Image: aws/codebuild/amazonlinux2-aarch64-standard:3.0
        PrivilegedMode: true
        EnvironmentVariables:
          - Name: AWS_DEFAULT_REGION
            Value: us-east-1
          - Name: AWS_ACCOUNT_ID
            Value: 292770788088
          - Name: IMAGE_TAG
            Value: latest
          - Name: IMAGE_REPO_NAME
            Value: !Ref ImageRepositoryName
          - Name: TASK_ARN
            Value: !Ref MyECSTaskDefinition
          - Name: CONTAINER_NAME
            Value: !Sub '${UniqueID}-container'
      Artifacts:
        Type: CODEPIPELINE
      Cache:
        Type: S3
        Location: !Sub '${UniqueID}-bucket/codebuild-cache'

  MyCodePipeline:
    Type: 'AWS::CodePipeline::Pipeline'
    Properties:
      Name: !Sub '${UniqueID}-MyCodePipeline'
      RoleArn: !GetAtt MyCodePipelineRole.Arn
      ArtifactStore:
        Location: !Ref MyS3Bucket
        Type: S3
      Stages:
        - Name: Source
          Actions:
            - Name: SourceAction
              ActionTypeId:
                Category: Source
                Owner: ThirdParty
                Provider: GitHub
                Version: 1
              OutputArtifacts:
                - Name: SourceOutput
              Configuration:
                Owner: !Ref GitHubRepoOwner
                Repo: !Ref GitHubRepoName
                Branch: !Ref GitHubBranch
                OAuthToken: '{{resolve:secretsmanager:/test/github:SecretString:GitHubToken}}'

        - Name: Build
          Actions:
            - Name: BuildAction
              ActionTypeId:
                Category: Build
                Owner: AWS
                Provider: CodeBuild
                Version: 1
              InputArtifacts:
                - Name: SourceOutput
              OutputArtifacts:
                - Name: BuildOutput
              Configuration:
                ProjectName: !Ref MyCodeBuildProject

        - Name: Deploy
          Actions:
            - Name: DeployAction
              ActionTypeId:
                Category: Deploy
                Owner: AWS
                Provider: CodeDeploy
                Version: 1
              InputArtifacts:
                - Name: BuildOutput
              Configuration:
                ApplicationName: !Ref MyCodeDeployApplication
                DeploymentGroupName: !Ref MyCodeDeployDeploymentGroup

  MyCodeDeployApplication:
    Type: 'AWS::CodeDeploy::Application'
    Properties:
      ApplicationName: !Sub '${UniqueID}-MyCodeDeployApplication'
      ComputePlatform: ECS

  MyCodeDeployDeploymentGroup:
    Type: 'AWS::CodeDeploy::DeploymentGroup'
    Properties:
      ApplicationName: !Ref MyCodeDeployApplication
      DeploymentGroupName: !Sub '${UniqueID}-MyCodeDeployDeploymentGroup'
      ServiceRoleArn: !GetAtt MyCodeDeployRole.Arn
      DeploymentConfigName: CodeDeployDefault.ECSAllAtOnce
      DeploymentStyle:
        DeploymentType: BLUE_GREEN
        DeploymentOption: WITH_TRAFFIC_CONTROL
      ECSServices:
        - ClusterName: !Ref MyECSCluster
          ServiceName: !GetAtt MyECSService.Name
      AutoScalingGroups: [] # Add your Auto Scaling Group ARNs here if using Auto Scaling
      LoadBalancerInfo:
        TargetGroupPairInfoList:
          - TargetGroups:
              - !Ref MyTargetGroup
              - !Ref MySecondTargetGroup
            ProdTrafficRoute:
              ListenerArns:
                - !Ref MyALBListener

      BlueGreenDeploymentConfiguration:
        DeploymentReadyOption:
          ActionOnTimeout: CONTINUE_DEPLOYMENT
          WaitTimeInMinutes: 0
        TerminateBlueInstancesOnDeploymentSuccess:
          Action: TERMINATE
          TerminationWaitTimeInMinutes: 5

  MyCodeBuildRole:
    Type: 'AWS::IAM::Role'
    Properties:
      RoleName: !Sub '${UniqueID}-MyCodeBuildRole'
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: codebuild.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: !Sub '${UniqueID}-MyCodeBuildRolePolicy'
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: '*'
              - Effect: Allow
                Action:
                  - s3:GetObject
                  - s3:PutObject
                  - s3:GetBucketAcl
                Resource: !Sub 'arn:aws:s3:::${MyS3Bucket}/*'
              - Effect: Allow
                Action:
                  - ecr:BatchCheckLayerAvailability
                  - ecr:CompleteLayerUpload
                  - ecr:GetAuthorizationToken
                  - ecr:InitiateLayerUpload
                  - ecr:PutImage
                  - ecr:UploadLayerPart
                  - ecr:BatchGetImage
                  - ecr:GetDownloadUrlForLayer
                Resource: '*'

  MyCodePipelineRole:
    Type: 'AWS::IAM::Role'
    Properties:
      RoleName: !Sub '${UniqueID}-MyCodePipelineRole'
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: codepipeline.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: !Sub '${UniqueID}-MyCodePipelineRolePolicy'
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - s3:GetObject
                  - s3:PutObject
                  - s3:GetBucketVersioning
                  - s3:GetBucketAcl
                Resource: !Sub 'arn:aws:s3:::${MyS3Bucket}/*'
              - Effect: Allow
                Action:
                  - codebuild:StartBuild
                  - codebuild:BatchGetBuilds
                  - codebuild:BatchGetBuildBatches
                  - codebuild:StartBuildBatch
                Resource: '*'
              - Effect: Allow
                Action:
                  - codedeploy:CreateDeployment
                  - codedeploy:GetApplication
                  - codedeploy:GetApplicationRevision
                  - codedeploy:GetDeployment
                  - codedeploy:GetDeploymentConfig
                  - codedeploy:RegisterApplicationRevision
                Resource: '*'

  MyCodeDeployRole:
    Type: 'AWS::IAM::Role'
    Properties:
      RoleName: !Sub '${UniqueID}-MyCodeDeployRole'
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: codedeploy.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: !Sub '${UniqueID}-MyCodeDeployRolePolicy'
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - ecs:DescribeServices
                  - ecs:CreateTaskSet
                  - ecs:UpdateServicePrimaryTaskSet
                  - ecs:DeleteTaskSet
                  - elasticloadbalancing:DescribeTargetGroups
                  - elasticloadbalancing:DescribeListeners
                  - elasticloadbalancing:ModifyListener
                  - elasticloadbalancing:DescribeRules
                  - elasticloadbalancing:ModifyRule
                  - lambda:InvokeFunction
                  - cloudwatch:DescribeAlarms
                  - sns:Publish
                  - s3:GetObject
                  - s3:GetObjectVersion
                  - iam:PassRole
                Resource: '*'
# Outputs:
#   MyECSTaskDefinitionArn:
#     Value: !Ref MyECSTaskDefinition
#     Export:
#       Name: MyECSTaskDefinitionArn
#   MyContainerName:
#     Value: !Sub '${UniqueID}-container'
#     Export:
#       Name: MyContainerName
